### ISSUE TITLE
Add a link to the site source in the footer?

### ISSUE THREAD

**Issue by maelle** [Athanasiamo/DrMowinckels#14]
Just a suggestion :-)

**Comment by maelle** [comment]
And there's no link to the website from this repo ;-)

**Comment by Athanasiamo** [comment]
good suggestions! Thank you!

**Comment by Athanasiamo** [comment]
Both suggestions are now implemented:
footer: [52a90d](https://github.com/Athanasiamo/DrMowinckels/commit/52a90d7790bec504134f36cc8dc29dec5b468b3e)
readme: [c1c1d9477](https://github.com/Athanasiamo/DrMowinckels/commit/c1c1d9477d8ddb15ac44e3770fc5c37552a61010)

**Comment by maelle** [comment]
awesome!
